### ISSUE TITLE
Проверка ЛР6

### ISSUE THREAD

**Issue by DSG888** [DSG888/LR6#1]
Работу выполнил Дорогин Сергей

To: @evgeny-p

**Comment by evgeny-p** [comment]
По заданию в `README.md` нужно было включить status image, а не скопировать лог сборки. Указанная в данный момент информация станет устаревшей с очередной сборкой.

**Comment by DSG888** [comment]
Работу выполнил Дорогин Сергей

To: @evgeny-p

**Comment by evgeny-p** [comment]
Принято.
